src/Entity/Order/Cart.php
<?php 

namespace App\Entity\Order;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use LogicException;

class Cart
{
    const SESSION_CART_NAME = 'cart';
    const TAX_RATE = 10; 
    /**
     * @var Collection|Item[]
     */
    private $items;

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }
    public function addItem(Item $item): self
    {
        if($this->items->exists(function($i,Item $it) use ($item){
            return $it->getVariation()->getId() === $item->getVariation()->getId();
        })){
            $existItem = $this->items[$item->getVariation()->getId()];
            $quantite = $existItem->getQuantite();
            $existItem->setQuantite($quantite + $item->getQuantite()); 
        }else{ 
            $this->items[$item->getVariation()->getId()] = $item;
            $item->setCart($this);                    
        }

        return $this;
    }

    public function editItem(Item $item): self
    {
        $filter = $this->items->filter(function(Item $it) use ($item){
            return $it->getVariation()->getId() === $item->getVariation()->getId();
        });
        if($filter->count() != 1){
            throw new LogicException();
        }
        $filter->first()->setQuantite($item->getQuantite());

        return $this;
    }

    public function removeItem(Item $item): self
    {
        $filter = $this->items->filter(function(Item $it) use ($item){
            return $it->getVariation()->getId() === $item->getVariation()->getId();
        });

        if($filter->count() != 1){
            throw new LogicException();
        }

        $this->items->removeElement($item);
        if ($item->getCart() === $this) {
            $item->setCart(null);
        }
        unset($item);

        return $this;
    }

    public function getItems(): Collection
    {
        return $this->items;
    }

    public function getPrix(): ?float
    {
        $prix = 0;
        foreach($this->items as $item){
            $prix = $prix + $item->getPrix();
        }

        return $prix;
    }

    public function getShippement()
    {
        return round($this->getPrix() * (self::TAX_RATE / 100));
    }

    public function getTotal()
    {
        return $this->getPrix() + $this->getShippement();
    }
}

src/Entity/OrderItem.php
<?php

namespace App\Entity;

use App\Repository\OrderItemRepository;
use App\Entity\Traits\TimestampableTrait;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderItemRepository::class)
 */
class OrderItem
{
    use TimestampableTrait;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Variation::class, inversedBy="orderItems")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite;

    /**
     * @ORM\ManyToOne(targetEntity=Order::class, inversedBy="items")
     * @ORM\JoinColumn(nullable=false)
     */
    private $panier;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArticle(): ?Variation
    {
        return $this->article;
    }

    public function setArticle(?Variation $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getPanier(): ?Order
    {
        return $this->panier;
    }

    public function setPanier(?Order $panier): self
    {
        $this->panier = $panier;

        return $this;
    }

    public function equals(OrderItem $item): bool
    {
        return $this->getArticle()->getId() === $item->getArticle()->getId();
    }

    public function getTotal(): float
    {
        return $this->getArticle()->getPrix() * $this->getQuantite();
    }
}

src/Controller/Web/CheckoutController.php
<?php

namespace App\Controller\Web;

use Twig\Environment;
use App\Entity\Order\Cart;
use App\Gateway\CartManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;


/**
 * @Route("/checkout")
 */
class CheckoutController
{
    /** @var CartManagerInterface */
    private $cartManager;
    /** @var Environment $engine */
    private $engine;
    /** @var RouterInterface $router */
    private $router;
    public function __construct(
        CartManagerInterface $cartManager,
        Environment $engine,
        RouterInterface $router
    )
    {
        $this->cartManager = $cartManager;
        $this->engine = $engine;
        $this->router = $router;
    }

    /**
     * @Route("", name="web_checkout_index")
     */
    public function index(): Response
    {
        $cart = $this->cartManager->getCart();
        $count = $cart instanceof Cart && !$cart->getItems()->isEmpty();
        if($count){
            return new Response($this->engine->render('shop/checkout/index/page.html.twig', [
                'cart' => $cart
            ]));
        }

        return new RedirectResponse($this->router->generate('web_shop_index'));
    }
}

templates/shop/checkout/index/page.html.twig
{% extends 'front/base.html.twig' %}
{% block title %}
    {{ title('Caisse' | trans) }}
{% endblock %}

{% block banner %}
	{{ banner('Caisse' | trans) }}
{% endblock %}
{% block features %}
	{{ features() }}
{% endblock %}
{% block body %}
<section class="checkout_area section_gap">
    <div class="container-fluid">
        <div class="returning_customer">
            <div class="check_title">
                <h2>Returning Customer? <a href="#">Click here to login</a></h2>
            </div>
            <p>If you have shopped with us before, please enter your details in the boxes below. If you are a new
                customer, please proceed to the Billing & Shipping section.</p>
            <form class="row contact_form" action="{{ path('web_login') }}" method="post" novalidate="novalidate"  autocomplete="off">
                <div class="col-md-6 form-group p_star">
                    <input type="text" class="form-control" name="_username">
                    <span class="placeholder" data-placeholder="{{ 'security.login.username'|trans }}"></span>
                </div>
                <div class="col-md-6 form-group p_star">
                    <input type="password" class="form-control" name="password">
                    <span class="placeholder" data-placeholder="{{ 'security.login.password'|trans }}"></span>
                </div>
                <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}"/>
                <div class="col-md-12 form-group">
                    <button type="submit" value="submit" class="primary-btn">{{ 'security.login.btn'|trans }}</button>
                    <a class="lost_pass" href="{{ path('web_reset') }}">{{ 'security.forgot_password'|trans }}</a>
                </div>
            </form>
        </div>
        <div class="cupon_area">
            <div class="check_title">
                <h2>Have a coupon? <a href="#">Click here to enter your code</a></h2>
            </div>
            <input type="text" placeholder="Enter coupon code">
            <a class="tp_btn" href="#">Apply Coupon</a>
        </div>
        <div class="billing_details">
            <div class="row">
                <div class="col-lg-8">
                    <h3>Billing Details</h3>
                    <form class="row contact_form" action="#" method="post" novalidate="novalidate">
                        <div class="col-md-6 form-group p_star">
                            <input type="text" class="form-control" id="first" name="name">
                            <span class="placeholder" data-placeholder="First name"></span>
                        </div>
                        <div class="col-md-6 form-group p_star">
                            <input type="text" class="form-control" id="last" name="name">
                            <span class="placeholder" data-placeholder="Last name"></span>
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="text" class="form-control" id="company" name="company" placeholder="Company name">
                        </div>
                        <div class="col-md-6 form-group p_star">
                            <input type="text" class="form-control" id="number" name="number">
                            <span class="placeholder" data-placeholder="Phone number"></span>
                        </div>
                        <div class="col-md-6 form-group p_star">
                            <input type="text" class="form-control" id="email" name="compemailany">
                            <span class="placeholder" data-placeholder="Email Address"></span>
                        </div>
                        <div class="col-md-12 form-group p_star">
                            <select class="country_select">
                                <option value="1">Country</option>
                                <option value="2">Country</option>
                                <option value="4">Country</option>
                            </select>
                        </div>
                        <div class="col-md-12 form-group p_star">
                            <input type="text" class="form-control" id="add1" name="add1">
                            <span class="placeholder" data-placeholder="Address line 01"></span>
                        </div>
                        <div class="col-md-12 form-group p_star">
                            <input type="text" class="form-control" id="add2" name="add2">
                            <span class="placeholder" data-placeholder="Address line 02"></span>
                        </div>
                        <div class="col-md-12 form-group p_star">
                            <input type="text" class="form-control" id="city" name="city">
                            <span class="placeholder" data-placeholder="Town/City"></span>
                        </div>
                        <div class="col-md-12 form-group p_star">
                            <select class="country_select">
                                <option value="1">District</option>
                                <option value="2">District</option>
                                <option value="4">District</option>
                            </select>
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="text" class="form-control" id="zip" name="zip" placeholder="Postcode/ZIP">
                        </div>
                        <div class="col-md-12 form-group">
                            <div class="creat_account">
                                <input type="checkbox" id="f-option2" name="selector">
                                <label for="f-option2">Create an account?</label>
                            </div>
                        </div>
                        <div class="col-md-12 form-group">
                            <div class="creat_account">
                                <h3>Shipping Details</h3>
                                <input type="checkbox" id="f-option3" name="selector">
                                <label for="f-option3">Ship to a different address?</label>
                            </div>
                            <textarea class="form-control" name="message" id="message" rows="1" placeholder="Order Notes"></textarea>
                        </div>
                    </form>
                </div>
                <div class="col-lg-4">
                    <div class="order_box">
                        <h2>Your Order</h2>
                        <ul class="list">
                            <li><a href="#">Product <span>Total</span></a></li>
                            {% for item in cart.items %}
                                <li>
                                        <a href="#">
                                            {{ item.variation.produit.titre }} 
                                            <span class="middle">x {{ item.quantite }}</span> 
                                            <span class="last">{{ item.prix | format_number(0,'KMF') }}</span>
                                        </a>
                                    </li>
                            {% endfor %}
                        </ul>
                        <ul class="list list_2">
                            <li><a href="#">Subtotal <span>{{ cart.prix | format_number(0,'KMF') }}</span></a></li>
                            <li><a href="#">Shipping <span>Flat rate: {{ cart.shippement | format_number(0,'KMF') }}</span></a></li>
                            <li><a href="#">Total <span>{{ cart.total | format_number(0,'KMF') }}</span></a></li>
                        </ul>
                        <div class="payment_item">
                            <div class="radion_btn">
                                <input type="radio" id="f-option5" name="selector">
                                <label for="f-option5">Check payments</label>
                                <div class="check"></div>
                            </div>
                            <p>Please send a check to Store Name, Store Street, Store Town, Store State / County,
                                Store Postcode.</p>
                        </div>
                        <div class="payment_item active">
                            <div class="radion_btn">
                                <input type="radio" id="f-option6" name="selector">
                                <label for="f-option6">Paypal </label>
                                <img src="img/product/card.jpg" alt="">
                                <div class="check"></div>
                            </div>
                            <p>Pay via PayPal; you can pay with your credit card if you don’t have a PayPal
                                account.</p>
                        </div>
                        <div class="creat_account">
                            <input type="checkbox" id="f-option4" name="selector">
                            <label for="f-option4">I’ve read and accept the </label>
                            <a href="#">terms & conditions*</a>
                        </div>
                        <a class="primary-btn" href="#">Proceed to Paypal</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}