src/Entity/Order/Item.php
<?php 

namespace App\Entity\Order;

use App\Entity\Variation;

class Item
{
    /** @var Cart */
    private $cart;
    /** @var Variation */
    private $variation;
    /** @var int */
    private $quantite;

    public function getVariation(): ?Variation
    {
        return $this->variation;
    }

    public function setVariation(Variation $variation): void
    {
        $this->variation = $variation;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): void
    {
        $this->quantite = $quantite;
    }

    public function getPrix(): ?float
    {
        return $this->variation->getRelativePrice() * $this->quantite;
    }

    public function getCart(): ?Cart
    {
        return $this->cart;
    }

    public function setCart(?Cart $cart): self
    {
        $this->cart = $cart;

        return $this;
    }
}

src/Controller/Web/ShopController.php
<?php
namespace App\Controller\Web;

use Twig\Environment;
use App\Entity\Search\VariationSearch;
use App\Repository\VariationRepository;
use App\Form\Search\VariationSearchType;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\FormFactoryInterface;


/**
 * @Route("/shop")
 */
class ShopController
{
    /** @var FormFactoryInterface $form */
    private $form;
    /** @var Environment $engine */
    private $engine;
    /** @var PaginatorInterface $paginator */
    private $paginator;
    /** @var VariationRepository $variationRepository */
    private $variationRepository;
    public function __construct(
        FormFactoryInterface $form,
        Environment $engine,
        PaginatorInterface $paginator,
        VariationRepository $variationRepository
    ){
        $this->form = $form;
        $this->engine = $engine;
        $this->paginator = $paginator;
        $this->variationRepository = $variationRepository;
    }

    /**
     * @Route("", name="web_shop_index")
     */
    public function index(Request $request)
    {
        $search = new VariationSearch();
        $search->setPage($request->query->get('page',1));
        $search->setLimit($request->query->get('limit',3));
        $search->setOrder($request->query->get('order'));
        $searchForm = $this->form->create(VariationSearchType::class,$search);
        $searchForm->handleRequest($request);
        [$min , $max] = $this->variationRepository->findMinMax($search);
        $query = $this->variationRepository
            ->findBySearch($search)
            ->getQuery()
        ;
        $pager = $this->paginator->paginate($query,$search->getPage(),$search->getLimit());
        
        if($request->get('ajax')){
            return new JsonResponse([
                'content' => $this->engine->render('shop/includes/_list.html.twig',[
                    'items' => $pager
                ]),
                'pagination' => $this->engine->render('shop/includes/_pagination.html.twig',[
                    'items' => $pager
                ]),
                'pagesize' => $this->engine->render('shop/includes/_pagesizeselecter.html.twig'),
                'sorting' => $this->engine->render('shop/includes/_orderselecter.html.twig'),
                'min' => $min,
                'max' => ($min == $max) ? $min + 1 : $max
            ]);
        }
        return new Response($this->engine->render('shop/index/page.html.twig',[
            'pager' => $pager,
            'search_form' => $searchForm->createView(),
            'min' => $min,
            'max' => ($min == $max) ? $min + 1 : $max
        ]));
    }

    /**
     * @Route("/{sku}", name="web_shop_show")
     */
    public function show(Request $request)
    {
        $item = $this->variationRepository->findOne($request->attributes->get('sku'))->getQuery()->getOneOrNullResult();
        return new Response($this->engine->render('shop/show/page.html.twig',[
            'item' => $item
        ]));        
    }
}

templates/shop/includes/_content.html.twig
<div class="col-xl-9 col-lg-8 col-md-7">
    <!-- Start Filter Bar -->
    <div class="filter-bar d-flex flex-wrap align-items-center">
        <div class="sorting js-filter-sorting">
            {% include 'shop/includes/_orderselecter.html.twig' %}
        </div>
        <div class="sorting mr-auto js-filter-pagesize">
            {% include 'shop/includes/_pagesizeselecter.html.twig' %}
        </div>
        <div class="js-filter-pagination">
            {% include 'shop/includes/_pagination.html.twig' with {items:list} only %}
        </div>
    </div>
    <div class="page lattest-product-area pb-40 category-list js-filter-list">
        {% include 'shop/includes/_list.html.twig' with {items:list} only %}
    </div>
    <div class="filter-bar d-flex flex-wrap align-items-center">
        <div class="sorting js-filter-sorting">
            {% include 'shop/includes/_orderselecter.html.twig' %}
        </div>
        <div class="sorting mr-auto js-filter-pagesize">
            {% include 'shop/includes/_pagesizeselecter.html.twig' %}
        </div>
        <div class="js-filter-pagination">
            {% include 'shop/includes/_pagination.html.twig' with {items:list} only %}
        </div>
    </div>
    <!-- End Filter Bar -->
</div>

templates/shop/includes/_filter.html.twig
    <div class="sidebar-filter">
        {{ form_start(form,{
            'attr':{
                'autocomplete':'off',
                'class':'js-filter-form'
            }
        }) }}
            <div class="top-filter-head">Product Filters</div>
            <div class="common-filter">
                <div class="head">Article</div>
                {{ form_widget(form.titre,{
                    'attr':{
                        'class':'form-control'
                    }
                }) }}
            </div>
            <div class="common-filter">
                <div class="head">Catégories</div>
                    <ul>
                        {% for child in form.unites %}
                            <li class="filter-list">
                                {{ form_widget(child,{
                                    'attr':{
                                        'class':'pixel-radio'
                                    }
                                }) }}
                                {{ form_label(child,null,{
                                    'label_attr':{
                                        'class':'label-radio'
                                    }
                                }) }}
                            </li>
                        {% endfor %}
                    </ul>
            </div>
            <div class="common-filter">
                <div class="head">Marques</div>
                    <ul>
                        {% for child in form.marques %}
                            <li class="filter-list">
                                {{ form_widget(child,{
                                    'attr':{
                                        'class':'pixel-radio'
                                    }
                                }) }}
                                {{ form_label(child,null,{
                                    'label_attr':{
                                        'class':'label-radio'
                                    }
                                }) }}
                            </li>
                        {% endfor %}
                    </ul>
            </div>
            <div class="common-filter">
                <div class="head">Prix</div>
                <div class="price-range-area">
                    <div id="price-slider" data-min="{{ min }}" data-max="{{ max }}"></div>
                    <br>
                    <div class="input-group">
                        <span class="input-group-text">De</span>
                        {{ form_widget(form.min,{
                            'attr':{
                                'class':'form-control min-price',
                                'style':'width: 30%;'
                            }
                        }) }}
                        <span class="input-group-text" style="border-left: 0; border-right: 0;">à</span>
                        {{ form_widget(form.max,{
                            'attr':{
                                'class':'form-control max-price',
                                'style':'width: 30%;'
                            }
                        }) }} 
                    </div>
                </div> 
            </div>
            <div class="common-filter">
                <div class="head">Tailles</div>
                    <ul>
                        {% for child in form.tailles %}
                            <li class="filter-list">
                                {{ form_widget(child,{
                                    'attr':{
                                        'class':'pixel-radio'
                                    }
                                }) }}
                                {{ form_label(child,null,{
                                    'label_attr':{
                                        'class':'label-radio'
                                    }
                                }) }}
                            </li>
                        {% endfor %}
                    </ul>
            </div>
        {{ form_end(form) }}
    </div>

templates/shop/includes/_item.html.twig
<div class="col-lg-4 col-md-6" id="item-{{ item.id }}">
    <div class="card card-cascade card-ecommerce wider shadow mb-5 single-product">
        <!--Card image-->
        <div class="view view-cascade overlay text-center"> <img class="card-img-top" src="{{ vich_uploader_asset(item,'file') }}" alt="" /> <a>
                <div class="mask rgba-white-slight"></div>
            </a> </div>
        <!--Card Body-->
        <div class="card-body card-body-cascade text-center product-details">
            <div class="price">
                <h6>{{ item.relativePrice | format_number(0,'KMF') }}</h6>
                {% if item.indiscount() %}
                <h6 class="l-through old-price">{{ item.prix | format_number(0,'KMF') }}</h6>
                {% endif %}
            </div>
            <div class="prd-bottom">       

                <a data-toggle="modal" data-target="#showModal{{item.id}}" class="btn social-info">
					<i class="fa fa-eye"></i>
                </a>
            </div>
            <!--Card footer-->
            <div class="card-footer">
                <div class="row js-cart-actions{{ item.id }}">
                    {% include 'shop/cart/includes/_forms.html.twig' with {cart: app.session.get('cart'),produit: item} only %}
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'shop/includes/_modal.html.twig' with {item: item} only %}

templates/shop/includes/_list.html.twig
<div class="row">
    {% for item in items %}
        {% include 'shop/includes/_item.html.twig' with {item:item} only %}
    {% endfor %}  
</div>

templates/shop/includes/_modal.html.twig
	<!-- Modal Quick Product View -->
	<div class="modal fade" id="showModal{{item.id}}" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" role="document">
			<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="container-fluid">
					<div class="row">
						<div class="col-md-4">
							<img class="card-img-top" src="{{ vich_uploader_asset(item,'file') }}" alt="" />
						</div>
						<div class="col-md-8">
							{% include 'shop/includes/_table_details.html.twig' with {item:item} only %}				
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary">Understood</button>
			</div>
			</div>
		</div>
	</div>

templates/shop/includes/_orderselecter.html.twig
{{ order_selecter() }}

templates/shop/includes/_pagesizeselecter.html.twig
{{ limit_selecter() }}

templates/shop/includes/_pagination.html.twig
{{ knp_pagination_render(items) }}

templates/shop/includes/_table_details.html.twig
<table class="table">
    <tbody>
        <tr>
            <th>
                {{ 'entity.variation.list.fields.sku' | trans }}
            </th>
            <td>{{ item.sku }}</td>
        </tr>
        <tr>
            <th>
                {{ 'entity.variation.form.fields.produit' | trans }}
            </th>
            <td>{{ item.produit.titre }}</td>
        </tr>
        {% if item.taille %}
        <tr>
            <th>
                {{ 'entity.variation.form.fields.taille' | trans }}
            </th>
            <td>{{ item.taille.valeur }}</td>
        </tr>
        {% endif %}
        {% if item.poids %}
        <tr>
            <th>
                {{ 'entity.variation.form.fields.poids' | trans }}
            </th>
            <td>{{ item.poids.valeur }}</td>
        </tr>
        {% endif %}
    </tbody>
</table>